version: '3.3'
services:
  espresso: 
    build: .
    volumes:
      - ./requirements.txt:/app/requirements.txt
      - ./crawler:/app/crawler
      - ./management:/app/management
      - ./scrapy.cfg:/app/scrapy.cfg
      - ./data:/app/data
      - ./manage.py:/app/manage.py
